<table align="center" width=100%>
    <tr>
        <td width="15%">
            <img src="homework.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> Take-Home <br>(Day 4)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Import the required libraries**

In [1]:
# import 'pandas' 
import pandas as pd 

# import 'numpy' 
import numpy as np

# to suppress warnings 
from warnings import filterwarnings
filterwarnings('ignore')

# import statsmodels
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

# import 'stats' package from scipy library
from scipy import stats

# import the functions to perform Chi-square tests
from scipy.stats import chi2_contingency
from scipy.stats import chi2
from scipy.stats import chisquare

# function to perform post-hoc test
import statsmodels.stats.multicomp as mc



### Let's begin with some hands-on practice exercises

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. The sales manager at an electronics company wants to study if online sales of their products in 2019 follow the same distribution as the online sales of products in 2015. He collected the sample of 300 products sold in 2019. Help the manager to test his claim using p-value technique at a 99% confidence level.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

<img src='chi_2.png'>

In [2]:
observe_sold=np.array([85,90,125])
observe_sold

array([ 85,  90, 125])

In [9]:
exp_sale=np.array([0.38,0.20,0.42])*300
exp_sale

array([114.,  60., 126.])

In [10]:
chi_critical=stats.chi2.isf(0.01,df=(len(exp_sale)-1))
chi_critical

9.210340371976182

In [12]:
stat,pval=stats.chisquare(f_obs=observe_sold,f_exp=exp_sale)
stat,pval

(22.38512949039265, 1.3776246111575923e-05)

In [ ]:
#test stat is >9.21 and pval<0.01 so we reject the null hypothisis

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Use hypothesis testing to check if the type of car is dependent on the type of car's transmission. Test the hypothesis with 95% confidence.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

<img src='chi_ind.png'>

In [14]:
observ_transmission=np.array([[104,85,78],[35,61,72]])
observ_transmission

array([[104,  85,  78],
       [ 35,  61,  72]])

In [17]:
chi_critical=stats.chi2.isf(0.05,df=2)
chi_critical

5.991464547107983

In [24]:
stat,pval,exp_val,dof=stats.chi2_contingency(observed=observ_transmission,correction=False)
print(stat)
print(pval)
print(dof)
print(exp_val)

16.774829953535356
0.00022771516717561853
[[85.31724138 89.6137931  92.06896552]
 [53.68275862 56.3862069  57.93103448]]
2


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. A company produces leather belts on three different production lines. The number of defective belts produced by each line is recorded. Test if all the production lines produce on an average equal number of defective belts. Use the p-value technique to test at 5% level of significance.  </b>
                </font>
            </div>
        </td>
    </tr>
</table>

Use the data given in the excel file `defective_prod.xlsx`

In [27]:
df=pd.read_excel('defective_prod.xlsx')
df.head()

production_line  def_belts
0               A          5
1               C          2
2               B          3
3               A          4
4               C          1

In [29]:
obsv_value=df['production_line'].value_counts()
obsv_value

B    7
A    7
C    7
Name: production_line, dtype: int64

In [60]:
A=df[df['production_line']=='A']['def_belts']
B=df[df['production_line']=='B']['def_belts']
C=df[df['production_line']=='C']['def_belts']

In [61]:
stats.shapiro(df['def_belts'])

ShapiroResult(statistic=0.9259648323059082, pvalue=0.11425024271011353)

In [62]:
stats.levene(A,B,C)

LeveneResult(statistic=0.8375, pvalue=0.4489726403784061)

In [63]:
t=df['production_line'].nunique()
t

3

In [64]:
N=df['def_belts'].value_counts().sum()
N

21

In [65]:
f_critical=stats.f.isf(0.05,dfn=t-1,dfd=N-t)
f_critical

3.554557145661787

In [66]:
f_test,pval=stats.f_oneway(A,B,C)
f_test,pval

(0.8384615384615386, 0.44857788134106824)

In [ ]:
#fail to reject null hypothis

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. The company wants to decide their advertisement strategies for their new smartwatch. The manager collects the advertising cost (in dollars) for four different mediums. Test if the company is spending on average an equal amount on all the advertising mediums using a critical value approach with 99% confidence.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

Use the data given in the excel file `ad_cost.xlsx`

In [21]:
df2=pd.read_excel('ad_cost.xlsx')
df2

medium  cost
0   Snapmart   252
1    Picbook   378
2     Funsta   312
3    Klicker   297
4    Picbook   361
5   Snapmart   274
6    Klicker   352
7    Picbook   343
8     Funsta   320
9   Snapmart   242
10   Klicker   305
11    Funsta   325

In [22]:
obsv_value=df2['medium'].value_counts()
obsv_value

Klicker     3
Picbook     3
Snapmart    3
Funsta      3
Name: medium, dtype: int64

In [23]:
w=df2[df2['medium']=='picbook']['cost']
x=df2[df2['medium']=='Klicker']['cost']
y=df2[df2['medium']=='Snapmart']['cost']
z=df2[df2['medium']=='Funsta']['cost']

In [24]:
stats.shapiro(df4['cost'])

ShapiroResult(statistic=0.9700301885604858, pvalue=0.9111207723617554)

In [25]:
t=df4['medium'].nunique()
t

4

In [26]:
N=df4['cost'].value_counts().sum()
N

12

In [27]:
f_critical=stats.f.isf(0.01,dfn=t-1,dfd=N-t)
f_critical

7.590991947598852

In [29]:
f_test,pval=stats.f_oneway(w,x,y,z)
f_test,pval

(nan, nan)